export const uiTheme = {
  buttonDefaultBgColor: '#000',
  buttonDefaultLabelColor: '#fff',
  buttonFont: 'Helvetica',
  buttonLinkLabelColor: '#075082',
  buttonPrimaryBgColor: '#075082',
  buttonPrimaryLabelColor: '#fff',
  buttonSecondaryBgColor: '#08637e',
  buttonSecondaryLabelColor: '#fff',

  inputFieldBorderColor: 'rgba(50, 50, 50, 0.5)',
  inputFieldBorderWidth: 1,
  inputFieldDisabledColor: '#333',
  inputFieldErrorColor: '#D70303',
  inputFieldFont: 'Helvetica',
  inputFieldHelpSize: 12,
  inputFieldKeyboardAppearance: 'dark',
  inputFieldLabelColor: '#313131',
  inputFieldLabelSize: 13,
  inputFieldPlaceholderColor: '#ccc',
  inputFieldSelectionColor: '#10C3D2',
  inputFieldTextColor: '#313131',
  inputFieldTextSize: 18,

  selectPickerFont: 'Helvetica',
  selectPickerHeaderBg: '#075082',
  selectPickerHeaderHeight: 30,
  selectPickerHeight: 250,
  selectPickerLabelColor: '#fff',
  selectPickerLabelSize: 14,
  selectPickerOverlayBg: 'rgba(0, 0, 0, 0.9)',
  selectPickerSelectorBg: '#fff',

  tagAvailableBorderColor: 'rgba(255, 255, 255, 0.3)',
  tagAvailableTextColor: '#fff',
  tagFont: 'Helvetica',
  tagHeight: 30,
  tagSelectedBgColor: '#427C71',
  tagSelectedCloseBgColor: 'rgba(255, 255, 255, 0.3)',
  tagSelectedCloseTextSize: 20,
  tagTextColor: '#fff',
  tagTextSize: 14
};
